from hl3 import *

while True:
    set_img("""
        .RR..RR.
        RRRRRRRR
        RRRRRRRR
        RRRRRRRR
        RRRRRRRR
        .RRRRRR.
        ..RRRR..
        ...RR...
    """)
    utime.sleep(0.2)
    set_img("""
        .RR..RR.
        R..RR..R
        RRRRRRRR
        RRRRRRRR
        RRRRRRRR
        .RRRRRR.
        ..RRRR..
        ...RR...
    """)
    utime.sleep(0.2)
    set_img("""
        .RR..RR.
        R..RR..R
        R......R
        RRRRRRRR
        RRRRRRRR
        .RRRRRR.
        ..RRRR..
        ...RR...
    """)
    utime.sleep(0.2)
    set_img("""
        .RR..RR.
        R..RR..R
        R......R
        R......R
        RRRRRRRR
        .RRRRRR.
        ..RRRR..
        ...RR...
    """)
    utime.sleep(0.2)
    set_img("""
        .RR..RR.
        R..RR..R
        R......R
        R......R
        R......R
        .RRRRRR.
        ..RRRR..
        ...RR...
    """)
    utime.sleep(0.2)
    set_img("""
        .RR..RR.
        R..RR..R
        R......R
        R......R
        R......R
        .R....R.
        ..RRRR..
        ...RR...
    """)
    utime.sleep(0.2)
    set_img("""
        .RR..RR.
        R..RR..R
        R......R
        R......R
        R......R
        .R....R.
        ..R..R..
        ...RR...
    """)
    utime.sleep(0.2)
    show_text("This is Text", Color.BLUE, 0.02)
    utime.sleep(0.2)
    christmas()


